version: "4"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/client/src
    networks:
      - Syndic
  api:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server/src:/server/src
    networks:
      - Syndic    
networks:
  Syndic:
    external: true